# Generated by Django 4.0.5 on 2022-07-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='Ссылка на изображение'),
        ),
    ]
